/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class FrameNomorGenapGanjil extends javax.swing.JFrame {
    
    // Method untuk memfilter input hanya angka
private void hanyaAngka(java.awt.event.KeyEvent evt) {
    char input = evt.getKeyChar();

    // Periksa apakah karakter bukan angka dan bukan tombol backspace
    if (!Character.isDigit(input) && input != '\b') {
        evt.consume(); // Batalkan karakter yang tidak valid
        javax.swing.JOptionPane.showMessageDialog(this, "Hanya angka yang diperbolehkan!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
    }
}
    
   // Method untuk mengecek genap atau ganjil tanpa parameter
private void cekGenapGanjil() {
    try {
        // Ambil input dari text field
        String input = txtInput.getText();
        int number = Integer.parseInt(input);

        // Periksa genap atau ganjil
        if (number % 2 == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Angka " + number + " adalah Genap.");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Angka " + number + " adalah Ganjil.");
        }
    } catch (NumberFormatException e) {
        // Jika input tidak valid
        javax.swing.JOptionPane.showMessageDialog(this, "Harap masukkan angka yang valid!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * Creates new form FrameNomorGenapGanjil
     */
    public FrameNomorGenapGanjil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        txtInput = new javax.swing.JTextField();
        labelAngka = new javax.swing.JLabel();
        btnCek = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        txtInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 11, 3, 11);
        jPanel1.add(txtInput, gridBagConstraints);

        labelAngka.setText("Input Angka:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 11, 3, 11);
        jPanel1.add(labelAngka, gridBagConstraints);

        btnCek.setText("Cek Nomor");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 11, 3, 11);
        jPanel1.add(btnCek, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
    cekGenapGanjil();    // TODO add your handling code here:
    }//GEN-LAST:event_btnCekActionPerformed

    private void txtInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyTyped
     hanyaAngka(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameNomorGenapGanjil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameNomorGenapGanjil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameNomorGenapGanjil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameNomorGenapGanjil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameNomorGenapGanjil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCek;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAngka;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
